drop table if exists alerts;

CREATE TABLE alerts (
                        "alertId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        "current" BOOLEAN NULL,
                        "expired" BOOLEAN NULL,
                        "urgency" TEXT NOT NULL,
                        "datePosted" TEXT NOT NULL,
                        "dateExpire" TEXT NOT NULL,
                        "to" TEXT NULL,
                        "toUserId" INTEGER NULL,
                        "from" TEXT NOT NULL,
                        "fromUserId" INTEGER NOT NULL,
                        "groupId" INTEGER NOT NULL,
                        "alertMessage" TEXT NOT NULL

);
