drop table if exists messages;

CREATE TABLE messages (
    messageId INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "date" TEXT NOT NULL,
    "to" TEXT NOT NULL,
    "toUserId" INTEGER NOT NULL,
    "from" TEXT NOT NULL,
    "fromUserId" INTEGER NOT NULL,
    "subject" TEXT NOT NULL,
    "subjectId" INTEGER NOT NULL,
    "messageContent" TEXT NOT NULL,
    "groupId" INTEGER NOT NULL
);
