drop table if exists bills;

CREATE TABLE bills (
    "billId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "tenant" TEXT NOT NULL,
    "tenantId" INTEGER NOT NULL,
    "manager" TEXT NOT NULL,
    "managerId" INTEGER NOT NULL,
    "rentFor" TEXT NOT NULL,
    "dueDate" TEXT NOT NULL,
    "totalDue" INTEGER NOT NULL,
    "pastDue" INTEGER NOT NULL,
    "basicRent" INTEGER NOT NULL,
    "water" INTEGER NOT NULL,
    "maintenance" INTEGER NOT NULL,
    "amountPaid" INTEGER NOT NULL,
    "paidDate" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "paidWith" TEXT NULL
);
